name    'domcleal-augeasprovider-shellvar'
version '1.0.0'
source 'git://github.com/hercules-team/augeasprovider-shellvar'
author 'Dominic Cleal, Raphael Pinson'
license 'Apache 2.0'
summary 'Augeas-based shellvar type and provider for Puppet'
description 'This module provides a type and provider to edit shellvar files in Puppet using the Augeas configuration API library.'
project_page 'http://github.com/hercules-team/augeasprovider-shellvar'
